### ISSUE TITLE
どのパッケージが更新されたか分からない (homebrew_upgrade_all: yes 指定時)

### ISSUE THREAD

**Issue by ryunix** [ryunix/ansible-role-homebrew#1]
現状は以下の通り。
個別に changed が出力される方が良い気がする。

```yaml
---
- hosts: all
  gather_facts: no
  roles:
    - role: homebrew
      homebrew_upgrade_all: yes
      homebrew_packages:
        - { name: ansible }
        - { name: bash }
```

```console
TASK: [homebrew | homebrew upgrade_all=True] **********************************
changed: [127.0.0.1]

TASK: [homebrew | homebrew name={{ item.name }} state={{ item.state | default(omit) }} install_options={{ item.install_options | default(omit) }}] ***
ok: [127.0.0.1] => (item={'name': 'ansible'})
ok: [127.0.0.1] => (item={'name': 'bash'})
```

**Comment by ryunix** [comment]
こうすれば個別に changed が出力されるが、もっと良いやり方があるはず。

```yaml
---
- hosts: all
  gather_facts: no
  roles:
    - role: homebrew
      homebrew_upgrade_all: no
      homebrew_packages:
        - { name: ansible, state: latest }
        - { name: bash, state: latest }
```

既定の state を変数にして、以下の優先順で設定すると良さそう。
個別の state > 既定の state
